### ISSUE TITLE
The min requirement should be set to php 5.5.*

### ISSUE THREAD

**Issue by mwidmann** [namnv609/php-onesignal-sdk#6]
Neither `guzzlehttp` nor `symphony-resolver` work on php 5.4 and therefore the library can't be used in php 5.4. 

The first issue occurring is that `::class` used in OptionsResolver.php is not available until php 5.5

`
HP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in ..../vendor/symfony/options-resolver/OptionsResolver.php on line 786
`

**Comment by namnv609** [comment]
@mwidmann Thanks for your feedback. I'll fix it in next few days :smiley:!

**Comment by namnv609** [comment]
This issue has been fixed!

Thank you for your contributing :heart:!

https://github.com/namnv609/php-onesignal-sdk/releases
