### ISSUE TITLE
Doesnt allow for spesific player_id

### ISSUE THREAD

**Issue by bocek** [namnv609/php-onesignal-sdk#7]
I want to send notif to a spesific user which is done with include_player_ids parameter. onesignal api says you cannot use include_player_ids with included_segments , you should choose one. But this sdk doesnt allow to remove included_segments from parameters when creating notification.

**Comment by namnv609** [comment]
# Change logs

## v1.0.1
  * Fix issue #7
  * Fix issue #6

## v1.0

  * Lauched

**Comment by namnv609** [comment]
This issue has been fixed!

Thank you for your contributing :heart:!

https://github.com/namnv609/php-onesignal-sdk/releases
